services:
    frontend:
        build:
            context: ./client
        ports:
            - '3000:3000'
        depends_on:
            - backend
        command: npm run dev
        develop:
            watch:
                - action: sync
                  path: ./client
                  target: /app
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json
        networks:
            - crm-network

    backend:
        build:
            context: ./server
        ports:
            - '5000:5000'
        command: npm run dev
        depends_on:
            - mongo
        environment:
            - PORT=5000
            - MONGO_URI=mongodb://mongo:27017/store-hub-crm
        develop:
            watch:
                - action: sync
                  path: ./server
                  target: /app
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json
        networks:
            - crm-network

    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongodb-data:/data/db
        networks:
            - crm-network

networks:
    crm-network:
        driver: bridge

volumes:
    mongodb-data:
        driver: local
