services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - crm-network

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - crm-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
