services:
    backend:
        build:
            context: ./
        ports:
            - '5000:5000'
        command: npm run dev
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://mongo:27017/test
        develop:
            watch:
                - action: sync
                  path: ./
                  target: /app
                  ignore:
                      - node_modules/
                - action: rebuild
                  path: package.json
        networks:
            - crm-network

    mongo:
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongodb-data:/data/db
        networks:
            - crm-network

networks:
    crm-network:
        driver: bridge

volumes:
    mongodb-data:
        driver: local
